{% set name = "napari-crop" %}
{% set version = "0.1.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 43e62a02ad5b48e338d86754edcd0974c021d07fef2306916f5466e093d68161

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - napari-plugin-engine >=0.1.4
    - napari-tools-menu
    - numpy
    - python >=3.7
    - scikit-image
    - napari-workflows

test:
  imports:
    - napari_crop
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/biapol/napari-crop
  summary: Crop regions in napari manually
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - haesleinhuepf
    - zoccoler
