{% set name = "napari-crop" %}
{% set version = "0.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-crop-{{ version }}.tar.gz
  sha256: e2b0c642df9e3345f43590c66a4a942a089d470cdba422291e8ddc2dbd008774

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - napari-plugin-engine >=0.1.4
    - napari-tools-menu
    - numpy
    - python >=3.7
    - scikit-image

test:
  imports:
    - napari_crop
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/biapol/napari-crop
  summary: Crop regions in napari manually
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - haesleinhuepf
